### ISSUE TITLE
Checklist for final milestone submission

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#289]
**For CS2103T**

- [x] Tag latest commit with `v1.4` and make release on GitHub
- [x] Generate `jar` file named `[F10-4][MeNUS].jar` and upload to release on GitHub and IVLE
- [x] Generate UserGuide pdf named `[F10-4][MeNUS]UserGuide.pdf` and upload to IVLE
- [x] Generate DeveloperGuide pdf named `[F10-4][MeNUS]DeveloperGuide.pdf` and upload to IVLE
- [x] Double check product website is of latest and correct version (check `README.adoc`, `UI.png` and `AboutUs.adoc` for the github.io version. To ignore Netlify
- [x] INDIVIDUALLY, generate PPP pdf named `[F10-4][Your Name]Portfolio.pdf` and upload to IVLE. Check that link to PPP from `AboutUs.adoc` is correct from product website

**For CS2101**

- [x] Submit the same generated PPP for CS2103T to CS2101 workbin
- [x] Submit the same generated UG and DG for CS2103T to CS2101 workbin
